#!/usr/bin/python3
import subprocess as sp
import argparse
import re
import os

CHDIR = os.getcwd()


def main(args: dict):
    path = ""
    if args['release']:
        path = "Release"
    else:
        path = "Debug"

    try:
        os.mkdir(path)
    except FileExistsError:
        pass
    os.chdir(path)
    try:
        sp.run(["cmake", "-DCMAKE_EXPORT_COMPILE_COMMANDS=1",
                "-DCMAKE_BUILD_TYPE=" + path, ".."],
               capture_output=True, check=True)

        out = sp.run(["cmake", "--build", "."],
                     capture_output=True, check=True)
        out = re.search("Built target (.*)", str(out.stdout)).group(1)
        out = out[:len(out) - 3]

        if os.name != "posix":
            out += ".exe"

        os.chdir(CHDIR)
        sp.run(["./" + path + "/" + out] + args['stdin'])
    except sp.CalledProcessError:
        os.rmdir("../" + path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="do the cmake run thing",
        usage="cmakerun [--release | -r] ..")
    parser.add_argument("-r", "--release", action="store_true",
                        help="build using optimizations")
    parser.add_argument('stdin', nargs='*')
    args = parser.parse_args()
    args = vars(args)

    main(args)
