#!/usr/bin/python3
import re
import requests
from sys import argv

def sizeof_fmt(num, suffix="B"):
    for unit in ["", "Ki", "Mi", "Gi", "Ti", "Pi", "Ei", "Zi"]:
        if abs(num) < 1024.0:
            return f"{num:3.1f}{unit}{suffix}"
        num /= 1024.0
    return f"{num:.1f}Yi{suffix}"

regex = re.compile(
        r'^(?:http|ftp)s?://'
        r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?)|'
        r'localhost|' #localhost...
        r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})' # ...or ip
        r'(?::\d+)?' # optional port
        r'(?:/?|[/?]\S+)$', re.IGNORECASE)
repo = argv[1]

if len(argv) < 2:
    exit("Must enter name/URL of git repo")

if regex.match(argv[1]):
    count = 0
    start = repo.find("://")
    for idx in reversed(range(start, len(repo))):
        if repo[idx] == '/':
            count += 1
        if count == 2:
            repo = repo[idx + 1:]
            break
    if count != 2:
        exit("URL missing repo name")
elif repo.count('/') != 1:
    exit("Invalid repo name/URL")

if repo[-4:] == ".git":
    repo = repo[:-4]

req = requests.get(f"https://api.github.com/repos/{repo}")
if req.status_code != 200:
    exit("Failed to get repo info")

print(sizeof_fmt(req.json()['size'] * 1024))
